version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - ineffassign
    - unconvert
    - prealloc
    - gocritic
    - revive
    - goconst
    - cyclop

  exclusions:
    presets: []
    paths:
      - ^api/
    rules:
      - path: internal/utils/
        linters:
          - revive

issues:
  max-same-issues: 5
  max-issues-per-linter: 10

formatters:
  enable: []
   # - gofmt
   # - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint/v2
